#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-

import nltk
import os

from nltk.util import ngrams
from nltk import bigrams
from nltk import trigrams

from nltk.tokenize import RegexpTokenizer
from nltk.tokenize import word_tokenize
from nltk.tokenize import regexp_tokenize

import re
from collections import Counter
from collections import OrderedDict

import operator


class LangDetector():
	index = dict()
	languages = dict()

	# Add a new document to the learning
	def addDocument(self, document, language):
		if language not in self.languages:
			self.languages[language] = 0
		words = self.getWords(document)
		
		for match in words:
			ngrams = self.getNgrams(match, 3)
			for ngram in ngrams:
				if ngram not in self.index:
					self.index[ngram] = {}
				if language not in self.index[ngram]:
					self.index[ngram][language] = 0
				self.index[ngram][language] += 1
			self.languages[language] += len(ngrams)

	# DETECT
	def detect(self, document):
		words = self.getWords(document)
		ngrams = dict()
		for word in words:
			for ngram in self.getNgrams(word, 3):
				if ngram not in ngrams:
					ngrams[ngram] = 0
				ngrams[ngram] +=1
		total = sum(ngrams.values())
		
		scores = dict()
		ngrams=OrderedDict(sorted(ngrams.items(), key=lambda t: t[1], reverse = True))
		for ngram in ngrams :
			if ngram not in self.index:
				continue
			for language in self.index[ngram]:
				if language not in scores:
					scores[language] = 0
				score = (float(self.index[ngram][language]) / float(self.languages[language])) * (float(ngrams[ngram])/float(total))
				scores[language] += score
		
		scores=OrderedDict(sorted(scores.items(), key=lambda t: t[1], reverse = True))
		return scores
				
	# TOKENIZE
	def getWords(self, document):
		reg = re.compile('[0-9\W]+', re.UNICODE)
		text_preprocess = document.decode('utf-8').lower()
		proper_text = ""
		tokens = list()
		for item in re.split(reg,text_preprocess):
			if(item != ""):
				tokens.append(item.encode('utf-8', errors='replace'))
				proper_text += item + " "
		return tokens

	# MAKE NGRAMS
	def getNgrams(self, words, n):
		listNgrams = list()
		if(len(words)<=3):
			listNgrams.append(words)
			return listNgrams
		for i in range(len(words)-n+1):
			Ngrams = words[i:i+n]
			listNgrams.append(Ngrams)
		return listNgrams

test= LangDetector()
test.addDocument("""


Outside the classroom, Stallman pursued his studies with even more diligence, rushing off to fulfill his laboratory-assistant duties at Rockefeller University during the week and dodging the Vietnam protesters on his way to Saturday school at Columbia. It was there, while the rest of the Science Honors Program students sat around discussing their college choices, that Stallman finally took a moment to participate in the preclass bull session.

Over time, however, Lippman says her son learned to adjust. By age seven, she says, her son had become fond of standing at the front window of subway trains, mapping out and memorizing the labyrinthian system of railroad tracks underneath the city. It was a hobby that relied on an ability to accommodate the loud noises that accompanied each train ride. "Only the initial noise seemed to bother him," says Lippman. "It was as if he got shocked by the sound but his nerves learned how to make the adjustment."

For the most part, businesses ignored Stallman's entreaties. Still, for a few entrepreneurs, the freedom associated with free software was the same freedom associated with free markets. Take software ownership out of the commercial equation, and you had a situation where even the smallest software company was free to compete against the IBMs and DECs of the world.

In 1962, computer scientists and hackers involved in MIT's Project MAC, an early forerunner of the AI Lab, took steps to alleviate this frustration. Time-sharing, originally known as "time stealing," made it possible for multiple programs to take advantage of a machine's operational capabilities. Teletype interfaces also made it possible to communicate with a machine not through a series of punched holes but through actual text. A programmer typed in commands and read the line-by-line output generated by the machine.

Such speculation benefits from the fast and loose nature of most so-called " behavioral disorders" nowadays, of course. As Steve Silberman, author of " The Geek Syndrome," notes, American psychiatrists have only recently come to accept Asperger Syndrome as a valid umbrella term covering a wide set of behavioral traits.

As a single parent for nearly a decade-she and Richard's father, Daniel Stallman, were married in 1948, divorced in 1958, and split custody of their son afterwards-Lippman can attest to her son's aversion to authority. She can also attest to her son's lust for knowledge. It was during the times when the two forces intertwined, Lippman says, that she and her son experienced their biggest battles.

With no dorm and no desire to return to New York, Stallman followed a path blazed by Greenblatt, Gosper, Sussman, and the many other hackers before him. Enrolling at MIT as a grad student, Stallman rented an apartment in nearby Cambridge but soon viewed the AI Lab itself as his de facto home.

In 1962, computer scientists and hackers involved in MIT's Project MAC, an early forerunner of the AI Lab, took steps to alleviate this frustration. Time-sharing, originally known as "time stealing," made it possible for multiple programs to take advantage of a machine's operational capabilities. Teletype interfaces also made it possible to communicate with a machine not through a series of punched holes but through actual text. A programmer typed in commands and read the line-by-line output generated by the machine.

Hearing Breidbart's anecdote retold elicits a wry smile from Stallman. "I may have been a bit of a jerk sometimes," he admits. "But I found kindred spirits among the teachers, because they, too, liked to learn. Kids, for the most part, didn't. At least not in the same way."

The programming session lasted 10 hours. Throughout that entire time, Steele says, neither he nor Stallman took a break or made any small talk. By the end of the session, they had managed to hack the pretty print source code to just under 100 lines. "My fingers were on the keyboard the whole time," Steele recalls, "but it felt like both of our ideas were flowing onto the screen. He told me what to type, and I typed it."
There are several statistical approaches to language identification using different techniques to classify the data. One technique is to compare the compressibility of the text to the compressibility of texts in a set of known languages. This approach is known as mutual information based distance measure. The same technique can also be used to empirically construct family trees of languages which closely correspond to the trees constructed using historical methods.[citation needed] Mutual information based distance measure is essentially equivalent to more conventional model-based methods and is not generally considered to be either novel or better than simpler techniques. Bennedetto, et al.'s work has largely been discredited as relatively naive and inaccurate.

Another technique, as described by Cavnar and Trenkle (1994) and Dunning (1994) is to create a language n-gram model from a "training text" for each of the languages. These models can be based on characters (Cavnar and Trenkle) or encoded bytes (Dunning); in the latter, language identification and character encoding detection are integrated. Then, for any piece of text needing to be identified, a similar model is made, and that model is compared to each stored language model. The most likely language is the one with the model that is most similar to the model from the text needing to be identified. This approach can be problematic when the input text is in a language for which there is no model. In that case, the method may return another, "most similar" language as its result. Also problematic for any approach are pieces of input text that are composed of several languages, as is common on the Web.

For a more recent method, see Řehůřek and Kolkus (2009). This method can detect multiple languages in an unstructured piece of text and works robustly on short texts of only a few words: something that the n-gram approaches struggle with.

An older statistical method by Grefenstette was based on the prevalence of certain function words (e.g., "the" in English).

Wiki Loves Africa: share African cultural fashion and adornment pictures with the world!
Page semi-protected
Shakira
From Wikipedia, the free encyclopedia
For other uses, see Shakira (disambiguation).
This name uses Spanish naming customs: the first or paternal family name is Mebarak and the second or maternal family name is Ripoll.

Shakira
Shakira 2014.jpg
Shakira in 2014
Born 	Shakira Isabel Mebarak Ripoll
February 2, 1977 (age 38)
Barranquilla, Atlántico, Colombia
Residence 	Barcelona, Spain
Nationality 	Colombian
Occupation 	

    Singer songwriter record producer dancer philanthropist entrepreneur 

Years active 	1990–present
Partner(s) 	Gerard Piqué (2010–present)
Children 	2
Website 	shakira.com
Musical career
Genres 	

    Pop Latin pop rock en español dance folk world 

Instruments 	

    Vocals guitar drums percussion harmonica[1] 

Labels 	

    Columbia Epic Live Nation RCA Sony Music Latin 

Shakira Isabel Mebarak Ripoll (pronounced: [ʃaˈkiɾa isaˈβel meβaˈɾak riˈpol]; English /ʃəˈkɪərə/;[2] born February 2, 1977)[3] is a Colombian singer, songwriter, dancer, record producer, choreographer, and model. Widely known with many honorific nicknames as "The Queen Of Latin Pop", "The Undisputed Queen Of Dance", "The Crossover Queen", "The Queen Of Social Media", "The Queen Of Facebook" and "The Queen Of World Cup". Born and raised in Barranquilla, she began performing in school, demonstrating Latin, Arabic, and rock and roll influences and belly dancing abilities. Shakira released her first studio albums, Magia and Peligro, in the early 1990s, failing to attain commercial success; however, she rose to prominence in Latin America with her major-label debut, Pies Descalzos (1996), and her fourth album, Dónde Están los Ladrones? (1998).

Shakira entered the English-language market with her fifth album, Laundry Service. Its lead single, "Whenever, Wherever", became the best-selling single of 2002. Her success was solidified with her sixth and seventh albums Fijación Oral, Vol. 1 and Oral Fixation, Vol. 2 (2005), the latter of which spawned the best-selling song of the 21st century, "Hips Don't Lie". Shakira's eighth and ninth albums, She Wolf (2009) and Sale el Sol (2010), received critical praise but suffered from limited promotion due to her strained relationship with label Epic Records. Her official song for the 2010 FIFA World Cup, "Waka Waka (This Time for Africa)", became the biggest-selling World Cup song of all time. With over 950 million views, its music video is the ninth most-watched video on YouTube. Since 2013, Shakira has served as a coach on the American version of The Voice, having appeared in two of its seven seasons—fourth and sixth. Her tenth album, Shakira (2014), is preceded by its lead single, "Can't Remember to Forget You".

Shakira has won 407 awards, including five MTV Video Music Awards, two Grammy Awards, ten Latin Grammy Awards, seven Billboard Music Awards, 28 Billboard Latin Music Awards and has been Golden Globe-nominated. She has a star on the Hollywood Walk of Fame, and sold more than 200 million records worldwide, including 75 million albums and 70 million physical singles and more than 60 million digital tracks worldwide,[4][5][6][7] making her the best selling Latin artist of all time, She carries out well-known philanthropic activities through charity work and benefit concerts, notably her Pies Descalzos Foundation, her performance at the "Clinton Global Initiative" created by former U.S. President Bill Clinton, and her invitation to the Oval Office by President Barack Obama in February 2010 to discuss early childhood development.[8] As of 2014, she is listed as the 58th most powerful woman in the world by Forbes.[9] As of July 2014, Shakira has become the first person to reach 100 million followers on Facebook.[10]

Contents

    1 Early life
    2 Career
        2.1 1990–95: Beginnings
        2.2 1995–2000: Latin breakthrough
        2.3 2001–04: English transition with Laundry Service
        2.4 2005–07: Fijación Oral, Vol. 1 and Oral Fixation, Vol. 2
        2.5 2008–12: She Wolf and Sale el Sol
        2.6 2013–present: The Voice and Shakira
    3 Artistry
    4 Legacy
    5 Other ventures
    6 Personal life
    7 Activism
    8 Discography
    9 Tours
    10 Filmography
    11 See also
    12 References
    13 Further reading
    14 External links

Early life
Barranquilla, Colombia, where Shakira Mebarak was born.

Shakira Isabel Mebarak Ripoll was born on February 2, 1977 in Barranquilla, Colombia. She is the only child of Nidia Ripoll and William Mebarak Chadid. Her paternal grandparents emigrated from Lebanon to New York City, where her father was born.[11][12][13][14] Her father then emigrated to Colombia at age 5. The name Shakira is Arabic (شاكِرة, šākirah), meaning "grateful". It is the feminine form of the name Shakir (شاكر, šākir). From her mother, Nidia Ripoll, she has Spanish (Catalan and Castilian)[15][16] and Italian[17] ancestry. She was raised Roman Catholic and attended Catholic schools.[18] She has eight older half-siblings from her father's previous marriage.[19] Shakira spent much of her youth in Barranquilla, a city located on the northern Caribbean coast of Colombia. Shakira wrote her first poem, titled "La Rosa De Cristal" ("The Crystal Rose") when she was only four years old. As she was growing up, she was fascinated watching her father writing stories on a typewriter, and asked for one as a Christmas gift. She got a typewriter at the age of seven and has continued writing poetry since then. These poems eventually evolved into songs. When Shakira was two years old, an older half-brother was killed in a motorcycle accident and at the age of eight, Shakira wrote her first song, titled "Tus gafas oscuras" ("Your dark glasses"), which was inspired by her father, who for years wore dark glasses to hide his grief.[20]

When Shakira was four, her father took her to a local Middle Eastern restaurant, where Shakira first heard the doumbek, a traditional drum used in Arabic music and which typically accompanied belly dancing.[21] She started dancing on the table, and the experience made her realize that she wanted to be a performer. She enjoyed singing for schoolmates and teachers (and even the nuns) at her Catholic school, but in second grade was rejected for the school choir because her vibrato was too strong. The music teacher told her that she sounded "like a goat".[21][22] At school, she was often sent out of the class because of her hyperactivity.[23] She says she had also been known as "the belly dancer girl", as she would demonstrate every Friday at school a number she had learned.[21] "That's how I discovered my passion for live performance," she says.[19][24]

To instill gratitude in Shakira for her upbringing, her father took her to a local park to see orphans who lived there. The images stayed with her and she said to herself "one day I'm going to help these kids when I become a famous artist."[19]

Between the ages of 10 and 13, Shakira was invited to various events in Barranquilla and gained some recognition in the area.[25] It was at about this time that she met local theater producer Monica Ariza, who was impressed with her and as a result tried to help her career. During a flight from Barranquilla to Bogotá, Ariza convinced Sony Colombia executive Ciro Vargas to hold an audition for Shakira in a hotel lobby. Vargas held Shakira in high regard and, returning to the Sony office, gave the cassette to a song and artist director. However, the director was not overly excited and thought Shakira was something of "a lost cause". Vargas, not daunted, was still convinced that Shakira had talent, and set up an audition in Bogotá. He arranged for Sony Colombia executives to arrive at the audition, with the idea of surprising them with Shakira's performance. She performed three songs for the executives and impressed them enough for her to be signed to record three albums.[26]
Career
1990–95: Beginnings
Main articles: Magia and Peligro

Shakira's debut album, Magia, was recorded with Sony Music Colombia in 1990 when she was only 13 years old.[27] The songs are a collection made by her since she was eight, mixed pop-rock ballads and disco uptempo songs with electronic accompaniment, however it was hampered by a lack of recording and production cohesion. The album was released in June 1991 and featured "Magia" and three other singles. Though it fared well on Colombian radio and gave the young Shakira much exposure, the album did not fare well commercially as only 1,200 copies were sold worldwide.[21] After the poor performance of Magia, Shakira's label urged her to return to the studio to release a follow-up record. Although little known outside of her native Colombia, Shakira was invited to perform at Chile's Viña del Mar International Song Festival in February 1993. The festival gave aspiring Latin American singers a chance to perform their songs, and the winner was then chosen by a panel of judges. Shakira performed the ballad "Eres" ("You Are") and won the trophy for third place. One of the judges who voted for her to win was then 20-year-old Ricky Martin.[27]

Shakira's second studio album Peligro was released in March, but Shakira was not pleased with the final result, mainly taking issue with the production. The album was better received than Magia, though it was also considered a commercial failure due to Shakira's refusal to advertise it. Shakira then decided to take a hiatus from recording so that she could graduate from high school.[27] In the same year, Shakira starred in the Colombian TV series The Oasis, loosely based on the Armero tragedy in 1985.[28] Since then, the albums have been pulled from release and are not considered official Shakira albums but rather promotional albums. Shakira originally recorded the song "¿Dónde Estás Corazón?" (later released on her album Pies Descalzos) for the compilation album Nuestro Rock in 1995, released exclusively in Colombia.[29] The album Pies Descalzos brought her great popularity in Latin America by the hit singles "Estoy Aquí," "Pies Descalzos, Sueños Blancos" and "Dónde Estás Corazón."[27] Shakira also recorded three tracks in Portuguese titled "Estou Aqui", "Um Pouco de Amor", and "Pés Descalços".
1995–2000: Latin breakthrough
Main articles: Pies Descalzos, Dónde Están los Ladrones? and MTV Unplugged
Shakira during her Tour Anfibio

Shakira returned to recording music under Sony Music along with Columbia in 1995 with Luis F. Ochoa, using musical influences from a number of countries and an Alanis Morissette-oriented persona which affected two of her next albums.[30] These recordings spawned her third studio album and major-label debut Pies Descalzos. Recording for the album began in February 1995, after the success of her single "¿Dónde Estás Corazón?". Sony gave Shakira $100,000 to produce the album since they predicted that the album would not sell past 100,000 copies. Starting with this album, Shakira began producing her own music, perfecting her vocals and most of all, practicing creative control over her music. Highly influenced by the American alternative market and British groups such as The Pretenders, the album's songs are melodic, musically surprising and gritty, with intellectual lyrics and an electronic/acoustic blend that effectively broke the formulaic mold of Latin pop with an authentic sound that had not been heard before.[citation needed] The album, Pies Descalzos, was released in February 1996. It debuted at number one in eight different countries. However, it only managed to reach number one-hundred-eighty on the U.S. Billboard Hot 100 but reached number five on the U.S. Billboard Top Latin Albums chart. The album spawned six hit singles, "Estoy Aquí" which reached number two on the U.S. Latin chart, "¿Dónde Estás Corazón?" which reached number five on the U.S. Latin chart, "Pies Descalzos, Sueños Blancos" which reached number 11 on the U.S. Latin chart, "Un Poco de Amor" which reached number six on the U.S. Latin chart, "Antología" which reached number 15 on the U.S. Latin Pop Songs chart and "Se quiere, Se Mata" which reached number eight on the U.S. Latin chart.[31] In August 1996, RIAA certified the album platinum status.[32]

In March 1996, Shakira went on to her first international tour named simply the Tour Pies Descalzos. The tour consisted of 20 shows and ended in 1997. Also in that year, Shakira received three Billboard Latin Music Awards for Album of the Year for Pies Descalzos, Video of the Year for "Estoy Aqui" and Best New Artist.[33] Pies Descalzos later sold over 5 million copies,[34][35] prompting the release of a remix album, simply titled The Remixes. The Remixes also included Portuguese versions of some of her well known songs, which were recorded as a result of her success in the Brazilian market, where Pies Descalzos sold nearly one million copies.[25]

Her fourth studio album, Dónde Están los Ladrones?, produced entirely by Shakira herself and Emilio Estefan, Jr. as the executive producer, was released in September 1998. The album, inspired by an incident in an airport in which a suitcase full of her written lyrics was stolen, became a bigger hit than Pies Descalzos. The album has reached a peak position of number 131 on the U.S. Billboard 200 and held the top spot on the U.S. Latin Albums chart for 11 weeks. It has since sold over seven million copies worldwide[36][37][clarification needed] and 1.5 million copies in the U.S. alone, making it one of the best selling Spanish albums in the U.S. Eight singles were taken from the album including "Ciega, Sordomuda", "Moscas En La Casa", "No Creo" which became her first single to chart on the U.S. Billboard Hot 100, "Inevitable", "Tú", "Si Te Vas", "Octavo día", and the "Ojos Así". The latter two songs won Shakira one Latin Grammy each with six of the eight singles reaching the top 40 on the U.S. Latin chart.

Shakira also received her first Grammy Award nomination in 1999 for Best Latin Rock/Alternative Album.[38] Shakira's first live album, MTV Unplugged was recorded in New York City on August 12, 1999. Highly acclaimed by American critics, it is rated as one of her best-ever live performances.[39] The live album earned the Grammy Award for Best Latin Pop Album in 2001 and gained sales of five million worldwide. In March 2000, Shakira embarked on her Tour Anfibio, a two-month tour of Latin America and the United States. In August 2000, she won an MTV Video Music Award in the category of People's Choice — Favorite International Artist for "Ojos Así". In September 2000, Shakira performed "Ojos Así" at the inaugural ceremony of the Latin Grammy Awards, where she was nominated in five categories: Album of the Year and Best Pop Vocal Album for MTV Unplugged, Best Female Rock Vocal Performance for "Octavo Día", Best Female Pop Vocal Performance and Best Short Form Music Video for the video for "Ojos Así".[40] She won two Grammy awards.
2001–04: English transition with Laundry Service
Main articles: Laundry Service and The Mongoose Tour

Upon the success of Dónde Están los Ladrones? and MTV Unplugged, Shakira began working on an English crossover album.[41] She worked for over a year on new material for the album. "Whenever, Wherever" ("Suerte" in Spanish countries) was released as the first and lead single from her first English album and fifth studio album throughout the period of August 2001 and February 2002. The song took heavy influence from Andean music, including the charango and panpipes in its instrumentation. It became an international success by reaching number one in most countries. It was also her first success in the U.S., by reaching number six on the Hot 100. In 2003, Shakira wrote a song called "Come Down Love" with Tim Mitchell for the Hollywood movie The Italian Job starring South African actress Charlize Theron and Mark Wahlberg, but the song was not included on the soundtrack of the movie.
Shakira before entering the stage to her Tour of the Mongoose (2003)

Shakira's fifth studio album and first English language album Laundry Service (Servicio De Lavanderia in Latin America and Spain) was released on November 13, 2001. The album debuted at number three on the U.S. Billboard 200 chart selling over 200,000 records in its first week. The album was later certified triple platinum by the RIAA in June 2004 as well.[42] It helped to establish Shakira's musical presence in the mainstream North American market. Seven singles were taken from the album such as "Whenever, Wherever" / "Suerte", "Underneath Your Clothes", "Objection (Tango)" / "Te Aviso, Te Anuncio (Tango)", "The One", "Te Dejo Madrid", "Que Me Quedes Tú" and "Poem to a Horse". Because the album was created for the English language market, the rock and Spanish dance-influenced album gained mild critical success with some critics claimed that her English skills were too weak for her to write songs for it with Rolling Stone stating "she sounds downright silly" or "Shakira's magic is lost in translation." Shakira also was criticized by her Latin fans for seemingly abandoning her folk and rock roots in favor of contemporary American pop music. Despite this fact, the album became the best selling album of 2002, selling more than 20 million copies worldwide.[27][43][44][45] and became the most successful album of her career to date. Around this time, Shakira also released four songs for Pepsi for her promotion in the English markets: "Ask for More", "Pide Más", "Knock on My Door" and "Pídeme el Sol".

In 2002, at Aerosmith's MTV Icon in April 2002, Shakira performed "Dude (Looks Like a Lady)". She also joined Cher, Whitney Houston, Celine Dion, Mary J. Blige, Anastacia, and the Dixie Chicks for VH1 Divas Live Las Vegas. In September, she won the International Viewer's Choice Award at the MTV Video Music Awards with "Whenever, Wherever". She also won the Latin Grammy Award for the category of Best Short Form Music Video for the Spanish version of the video. In October, she won five MTV Video Music Awards Latin America for Best Female Artist, Best Pop Artist, Best Artist – North (Region), Video of the Year (for "Suerte"), and Artist of the Year. In November, she embarked on the Tour of the Mongoose with 61 shows occurring by May 2003. The tour was also her first worldwide tour, as legs were played in North America, South America, Europe and Asia. Shakira's label Sony BMG also released her Spanish greatest hits compilation Grandes Éxitos. A DVD and 10-track live album, called Live & Off the Record, was also released in 2004, reaching sales of three million worldwide, and commemorating the Tour of the Mongoose.
2005–07: Fijación Oral, Vol. 1 and Oral Fixation, Vol. 2
Main articles: Fijación Oral, Vol. 1, Oral Fixation, Vol. 2 and Oral Fixation Tour
Shakira on Tour Fijación Oral in 2007.

Shakira's sixth studio album, Fijación Oral, Vol. 1, was released in June 2005. The lead single from the album, "La Tortura" reached the top 40 of on the Hot 100. The song featured the Spanish balladeer Alejandro Sanz. Shakira became the first artist to perform a Spanish language song at the MTV Video Music Awards in 2005. Contrary to low expectations, the album was extremely well received. It debuted at number four on the Billboard 200 chart, selling 157,000 copies in its first week. It has since sold over two million copies in the U.S., earning an 11× Platinum (Latin field) certification from the RIAA. Due to its first week sales, the album became the highest debut ever for a Spanish language album. After only a day of release in Latin America, the album earned certifications. In Venezuela, it earned a Platinum certification, in Colombia, a triple Platinum certification, while in Mexico demand exceeded shipments and the album was unavailable after only one day of release. The album sold over one million copies in three days worldwide. Four other singles were also released from the album. "No", "Día de Enero", "La Pared" and "Las de la Intuición", with each single reaching number one in countries worldwide. Fijación Oral, Vol. 1 has since sold over four million copies worldwide.[37] On February 8, 2006, Shakira won her second Grammy Award with the win of Best Latin Rock/Alternative Album for Fijación Oral, Vol. 1.[46] She received four Latin Grammy Awards in November 2006, winning the awards for Record of the Year, Song of the Year for "La Tortura", Album of the Year and Best Pop Vocal Album for Fijación Oral, Vol. 1.[47]
Shakira at the Rock in Rio festival (2006)

The lead single for Shakira's seventh album, Oral Fixation, Vol. 2, "Don't Bother", failed to achieve chart success in the U.S. by missing the top 40 on the Hot 100. It did, however, reach the top 20 in most countries worldwide. Shakira's second English studio album and seventh studio album, Oral Fixation, Vol. 2 was released on November 29, 2005. The album debuted at number five on the Billboard 200, selling 128,000 copies in its first week. The album has gone on to sell 1.8 million records in the U.S., and over eight million copies worldwide.[48] Despite the commercial failure of the album's lead single in the U.S., it went on to spawn two more singles. "Hips Don't Lie", which featured Wyclef Jean, was released as the album's second single in February 2006. The song went on to become the highest selling single of the 21st century[49][50] and became Shakira's first number one single on the Billboard Hot 100, in addition to reaching number one in over 55 countries. Shakira and Wyclef Jean also recorded a Bamboo version of the song to serve as the official theme of the FIFA World Cup 2006. Shakira later released the third and final single from the album, "Illegal", which featured Carlos Santana, in November 2006. She then embarked on the Oral Fixation Tour, in June 2006. The tour consisted of 125 shows between June 2006 and July 2007 and visited all six continents. One show in Mexico City was performed for free, and earned an audience of over 200,000. This concert sets the record for the highest attendance of any concert in Mexican history. In February 2007, Shakira performed for the first time at the 49th Grammy Awards and earned the nomination for Best Pop Collaboration with Vocals for "Hips Don't Lie" with Wyclef Jean.

In late 2006, Shakira and Alejandro Sanz collaborated for the duet Te lo Agradezco, Pero No, which is featured on Sanz' album El Tren de los Momentos. The song was a top ten hit in Latin America, and topped the Billboard Hot Latin Tracks chart. Shakira also collaborated with Miguel Bosé on the duet "Si Tú No Vuelves", which was released in Bosé's album Papito. In early 2007, Shakira worked with American R&B singer Beyoncé for the track "Beautiful Liar", which was released as the second single from the deluxe edition of Beyoncé's album B'Day. In April 2007, the single jumped 91 positions, from 94 to three, on the Billboard Hot 100 chart, setting the record for the largest upward movement in the history of the chart at the time. It was also number one on the official UK Singles Chart. The song earned them a Grammy Award nomination for Best Pop Collaboration with Vocals. Shakira was also featured on Annie Lennox's song "Sing", from the album Songs of Mass Destruction, which also features other 23 other female singers.[51] In late 2007, Shakira and Wyclef Jean recorded their second duet "King and Queen". The song was featured on Wyclef Jean's 2007 album Carnival Vol. II: Memoirs of an Immigrant. Shakira wrote the lyrics and co-wrote the music for two new songs that are featured in the movie Love in the Time of Cholera, based on the acclaimed novel by Colombian author Gabriel García Márquez. García Marquez himself asked Shakira to write the songs.[52] The songs that Shakira lent to the soundtrack were "Pienso en ti", a song from Shakira's breakthrough album Pies Descalzos, "Hay Amores" and "Despedida". "Despedida" was nominated for Best Original Song at the 65th Golden Globe Awards.
2008–12: She Wolf and Sale el Sol
Main articles: She Wolf, Sale el Sol and The Sun Comes Out World Tour
Shakira performing with Usher and Stevie Wonder at the We Are One: The Obama Inaugural Celebration at the Lincoln Memorial (2009)

In early 2008, Forbes named Shakira the fourth top-earning female artist in music industry.[53] Then, in July, Shakira signed a $300 million contract with Live Nation, an international touring giant, for ten years.[54][55] The touring group also doubles as a record label which promotes but does not control the music their artists release. Shakira's contract with Epic Records called for three more albums as well – one in English, one in Spanish, and a compilation, but the touring and other rights of the Live Nation deal were confirmed to begin immediately. In January 2009, Shakira performed at the Lincoln Memorial "We Are One" festivities in honor of the inauguration of President Barack Obama. She performed "Higher Ground" with Stevie Wonder and Usher. In March, Shakira appeared on the album Cantora 1 by the Argentinian folk singer Mercedes Sosa on the song "La Maza", which both singers sang at the ALAS concert in Buenos Aires in May 2008.
Shakira at the Rock in Rio festival in 2008

"She Wolf", the lead single from Shakira's eighth studio album, premiered on July 13, 2009.[56][57][58] Shakira wrote and produced the song with John Hill, and Sam Endicott (lead singer and songwriter of The Bravery).[59] The Spanish version, titled "Loba", premiered on the same day as well. "She Wolf" and "Loba" then became available for digital download the following day.[45] The video for "She Wolf" premiered on MTV on July 30, 2009.[45] The single was successful worldwide, reaching number one in Latin America, number two in Germany, Ireland, Italy, Estonia and Spain, number three in Switzerland and Austria, number four in the UK, France and Greece, number five in Canada and Belgium, number six in Finland, number nine in Japan, and number eleven in the US. The album, She Wolf, was released in October 2009 internationally and on November 23, 2009 in the U.S. The album received mainly positive reviews from critics, but only managed to sell 89,000 copies in its first week in the U.S., earning the number fifteen spot on the Billboard 200. It has gone on to sell only 300,000 records in the U.S., becoming her least successful album there. However, the album has been moderately successful worldwide, having been certified Gold in Russia, Ireland, Switzerland, Poland, France, Argentina, Greece, and Hungary, Platinum in Spain, the United Kingdom, and the Middle East, 2x Platinum in Colombia and Mexico, and 3x Platinum in Taiwan. To date the album has sold 2 million copies worldwide, becoming Shakira's least successful studio album to date in terms of sales.[60]
Shakira in 2012

The album's second single, "Did It Again", was released in October 2009 and was originally due for a U.S. release, though this was later canceled. The single reached the top 40 in most countries worldwide. "Give It Up to Me", which featured Lil Wayne was released as the album's second U.S. single in November 2009 and reached the top 40 in Canada and in the U.S. The album's U.S. release was delayed in order for Shakira to record the song, which was originally due to be featured on its producer Timbaland's album, Timbaland Presents Shock Value II and would have featured Shakira. However, she chose to record it for her album with Timbaland's rap verse being scrapped in favor of a verse from Flo Rida. Plans for the single changed again when Lil Wayne requested to be featured on the song, with this later happening. The album's third and final single, "Gypsy", was released in February 2010 and reached the top 40 in Europe but failed to reach the top 40 in the U.S. or in South America, becoming a mildly successful single.

In May, Shakira collaborated with the South African group Freshlyground to create the official song of the 2010 FIFA World Cup in South Africa. "Waka Waka (This Time for Africa)", which is based on a traditional Cameroonian soldiers' Fang song named "Zangalewa" by the group Zangalewa or Golden Sounds.[61] The single later reached the top 20 in Europe, South America and Africa and the top 40 in the U.S. and was performed by Shakira at the World Cup kick-off and closing. It became the biggest-selling World Cup song of all time.[62][63]

In October 2010, Shakira released her ninth studio album, Sale el Sol. The album debuted at number-seven on Billboard 200 in its first week, and at the top spot on the Billboard Top Latin Albums. The lead single "Loca" was number one in many countries. The album had sold over 1 million copies worldwide in 6 weeks,[64] and over 4 million since its release.[65] In September, Shakira embarked on The Sun Comes Out World Tour, in support of her two most recent albums. The tour visited countries in North America, Europe, South America, Asia, and Africa with 107 shows in total. The tour was met with positive reactions from critics, who praised Shakira's stage presence and energy during her performances. On November 9, 2011, Shakira was honored as Latin Recording Academy Person of the Year and performed a cover of Joe Arroyo's song "En Barranquilla Me Quedo" at the Mandalay Bay Events Center as a tribute to the singer who died earlier that year.[66][67] In 2010 Shakira collaborated with rapper Pitbull for the song "Get It Started" which is the lead single from Pitbull's upcoming album Global Warming. The single was released on June 28, 2012.[68] She was also signed to Roc Nation under management purposes for her upcoming studio album.[69]
2013–present: The Voice and Shakira
Shakira and Carlinhos Brown at the closing show of the 2014 FIFA World Cup.

In November 2011 Shakira said about her tenth album: "I already started to write new material. I've begun to explore in the recording studio whenever I have time in Barcelona and here in Miami. I'm working with different producers and DJs, and I try to feed off from that and find new sources of inspiration and new musical motivation. I'm anxious to return to the studio. My body is asking for it".[70] She worked with producers such as Benny Blanco, Tiësto, RedOne, Max Martin, Dr. Luke, LMFAO, Akon,[71] Fernando Garibay, Sia, Ester Dean,[72] Skrillex, The Runners, The-Dream, Tricky Stewart, Shea Taylor and Billboard.[73] Originally, the first single from her new album was expected to be a song named "Truth or Dare".[74] The music video was filmed in Lisbon on June 29, 2012.[75] But due to her unexpected pregnancy, plans to release the single and video were postponed.

On September 17, 2012, it was announced that Shakira and Usher would replace Christina Aguilera and CeeLo Green for the fourth season of the U.S. TV show The Voice, alongside Adam Levine and Blake Shelton. Shakira announced that she would focus on her new album in the fall and eventually returned for the show's sixth season in February 2014. On September 1, 2013, Shakira gave an update on her album, stating: "Amazing day in the studio! 2 years and I finally feel in these songs as comfortable as [I do] in my torn jeans!".[76]

Peter Edge - the CEO of RCA Records - told Billboard magazine in October 2013: "[There's this] new song from Shakira that's gonna be an event single, we plan on having it out before the end of [2013]".[77] On November 23, 2013, Shakira stated that she was writing the final lyrics for the album.[78] In December 2013, it was announced that Shakira's new single had been delayed until January 2014 and that the featured artist on the song is Rihanna.[79][80] On December 8, 2013, Shakira tweeted: "I just finished the video for my first single with director Joseph Kahn!".[81] On January 6, 2014, both Shakira and Rihanna tweeted that the new single would be titled "Can't Remember to Forget You". The single was released on January 13, 2014.[82][83] Shakira's self-titled tenth studio album was later released on March 25, 2014.[84]

On July 13, 2014, Shakira performed "La La La (Brazil 2014)" with Brazilian musician Carlinhos Brown at the 2014 FIFA World Cup closing ceremony at the Maracanã Stadium.[85] This performance became her third consecutive appearance at the FIFA World Cup.[86][87]

On August 14, 2015, at Disney's D23 Expo, it was announced that Shakira would be playing a character in the upcoming Disney animated movie, Zootopia, as Gazelle, the biggest pop star in Zootopia. Shakira will also contribute to the film an original song, titled "Try Everything", which has been written by Sia and Stargate.[88][89]
Artistry
Shakira in 2010.

Shakira is known to have adopted many genres, including folk, mainstream pop and rock. In an interview with Rolling Stone she said: "My music, I think, is a fusion of many different elements. And I'm always experimenting. So I try not to limit myself, or put myself in a category, or... be the architect of my own jail".[90] Her earlier Spanish albums, including Pies Descalzos and Dónde Están los Ladrones? were a mix of folk music and Latin rock. Her cross-over English album, Laundry Service and later albums were influenced by pop rock and pop Latino.[91] "Laundry Service" is primarily a pop rock album, but also draws influences from a variety of musical genres.[92] The singer credited this to her mixed ethnicity, saying "I am a fusion. That's my persona. I'm a fusion between black and white, between pop and rock, between cultures - between my Lebanese father and my mother's Spanish blood, the Colombian folklore and Arab dance I love and American music."[93] Arabian and Middle Eastern elements, which had a high influence on Dónde Están los Ladrones?,[93] are also present in Laundry Service, most prominently on "Eyes Like Yours" (Ojos Así).[94] Musical styles from different South American countries surface on the album. Tango, a style of fast-paced ballroom dance that originated in Argentina, is evident on "Objection (Tango)", which also combines elements of rock and roll.[92] The uptempo track features a guitar solo and a bridge in which Shakira delivers rap-like vocals.[95]

She Wolf is primarily an electropop album that combines influences from the musical styles of various countries and regions, like Africa, Colombia, India, and the Middle East.[96][97] Shakira termed the album as a "sonic experimental trip", and said that she researched folk music from different countries in order to "combine electronics with world sounds, tambourines, clarinets, oriental and Hindu music, dancehall, etc."[98] Her 2010 album, Sale el Sol, is a return to her beginnings containing ballads such as "Lo Que Más" and "Antes de las Seis", rock songs like "Tu Boca" and "Devoción", and Latin dance songs like "Loca".[99][100] Shakira possesses a contralto vocal range.

I have been a Cerati fan all my life when he was part of Soda Stereo and before knowing him I had already gone to three of his concerts. Both Gustavo [Cerati] and Santana have enriched me, they are my small wonders.
“
”
 — Shakira in 2006 speaking on Spanish language rock and how she is indebited to the Argentine rock power trio Soda Stereo and to the Mexican American band Santana.[101]

Shakira has told many interviewers that she has grown fond of listening to oriental music, which influenced many of her earlier works. For example, Shakira used the Indian theme for her performance of "Hips Don't Lie" at the 2006 MTV Video Music Awards in New York City.[102] She has also been influenced by her Arab heritage, which was a major inspiration for her breakthrough world hit "Ojos Así". She told Portuguese TV "Many of my movements belong to Arab culture." She also cites her parents as major contributors to her musical style.[103] In childhood, Shakira preferred rock and roll music, listening heavily to her favorite rock bands like Led Zeppelin,[104] The Beatles, Nirvana, The Police and U2.[105] She lists John Lennon as her No.1 musical influence. She was also deeply influenced by Prince, The Rolling Stones, AC/DC, The Who, The Pretenders, Red Hot Chili Peppers, The Cure, Tom Petty, Depeche Mode, The Clash, Ramones, whose influence can be heard on her many prominent songs.[106] In a recent interview to Elenco magazine, she noted that in her opinion the perfect songs are "Imagine" by John Lennon and "No Woman, No Cry" by Bob Marley.[107]

Shakira made several covers of prominent artists such AC/DC and Aerosmith, using them to sing in her tours, resulting in performances of "Back in Black"[108] and "Dude (Looks Like a Lady)" during her Tour of the Mongoose. She also sang the classic Elvis Presley song "Always on My Mind" at the VH1 Divas Live.[citation needed] In her 2010–2011 tour called The Sun Comes Out World Tour, she sings "Nothing Else Matters" by the heavy metal band Metallica in an oriental style. She is also strongly influenced by Andean music and South American folk music, using her native instrumentation for the Latin dance-pop "Whenever, Wherever" and "Despedida".[109] Shakira recently[when?] performed two songs for two separate Haiti benefit events: "I'll Stand By You", by The Pretenders, and "Sólo le pido a Dios" by León Gieco.

Shakira is well known for her dancing in various music videos and in concert. Her moves are based on the art of belly dancing, a part of her Lebanese heritage. She often performs barefoot. Shakira says she learned this form of dance as a young teen to overcome her shyness. She also mentioned in a MTV interview that she learned how to belly dance by trying to flip a coin with her belly.[110][111] The intense training has afforded her a fluidity in her body movement most seen in the videos to her hits "Ojos Así", "La Tortura", "Hips Don't Lie", "Whenever, Wherever / Suerte", "Beautiful Liar" and "She Wolf / Loba". She has had several belly dance choreographers, including award-winning Bellydance Superstar Boženka.[112] As the MTV Making the Video for "La Tortura" reveals, she worked with Jamie King on the choreography, but ended up creating most of it herself.
Legacy
Main article: List of awards and nominations received by Shakira
Statue of Shakira in Barranquilla, Colombia

According to Sony, Shakira is the highest-selling Colombian artist of all time, having sold between 50 and 60 million records.[113] According to Nielsen Broadcast Data Systems, "Hips Don't Lie" was the most-played pop song in a single week in American radio history. It was played 9,637 times in one week. Shakira became the first artist in the history of the Billboard charts to earn the coveted number one spots on both the Top 40 Mainstream and Latin Chart in the same week doing so with "Hips Don't Lie".[114] Her song "La Tortura" broke the record on the Billboard's Hot Latin Tracks chart, appearing at number-one more than any other single with a total of 25 non-consecutive weeks.[115]

According to Yahoo!, her song "Hips Don't Lie" is the best-selling single of the last decade.[50] According to Forbes Magazine, Shakira was the fourth highest-earning woman in music for 2008 behind Madonna, Barbra Streisand and Celine Dion.[116] According to Nokia in 2010, there were more Shakira music downloads in the prior year than for any other Latino artist in the last five years, and She Wolf topped the Top 10 Latino downloads.[117] Additionally, she is the only artist from South America to reach the number-one spot on the U.S. Billboard Hot 100, the Australian ARIA chart, and the UK Singles Chart.[118] In 2010, she was ranked number five on the 'Online Video's Most Viral Artists of 2010' with 404,118,932 views.[119] She has become a YouTube sensation having surpassed 1 billion views on the website with "Waka Waka" accounting for over 550 million views. She is the third person ever to have done this, after Lady Gaga and Justin Bieber.[120][121][122] On July 18, 2014, Shakira became the first person to reach 100 million likes on Facebook.[10]

In 2011, Shakira was honored at the Latin Grammys as 2011's Latin Recording Academy Person of the Year.[123] She also received a star on the Hollywood Walk of Fame located at 6270 Hollywood Blvd.[124][125] Originally, she was to be given a star on the Hollywood Walk of Fame in 2004, but she turned the offer down.[126] In 2012, she received the honor of Chevalier De L'Ordre des Arts et des Lettres.[127]

Shakira is the first musical act to perform three times at the FIFA World Cup.[87]
Other ventures
A bottle of S by Shakira, the first women's fragrance by Shakira

Shakira appeared in the Colombian telenovela El Oasis in 1994, playing the character of Luisa Maria.[128] In December 2009, Shakira appeared as herself in the Ugly Betty episode "The Bahamas Triangle".[129] In 2010, Shakira appeared as a fictional version of herself in an episode of Wizards of Waverly Place. She was also mentioned several times on the George Lopez TV series.[130] She was invited personally by Gabriel Garcia Marquez to play a role in Love in the Time of Cholera, but declined due to the nudity involved.[131]
S by Shakira. Logo used for her fragrance line

Shakira became the 2010 celebrity spokesperson for the Freixenet traditional Christmas TV commercial. Each year, this Cava company taps into a world-famous celebrity to be the face of its much-awaited holiday TV spot. For her latest venture, Shakira dressed up as a golden sparkling wine bubble, "This year, let's toast so that the sun shines more than ever. The best is yet to come. Merry Christmas," Shakira says in the ad. In a press conference in Barcelona, Shakira presented the Christmas commercial, which will start airing in Spain on December 9. Shakira also took the opportunity to announce that she used the $500,000 EUR ($662,085 USD) honorarium given to her by the Spanish bubbly to finance two schools run by her foundation, Pies Descalzos. The partnership between Shakira and Freixenet also includes a Pies Descalzos Foundation promotional video, directed by longtime Shakira collaborator and fellow Catalan Jaume Delaiguana.[132]

Shakira began her own beauty line, "S by Shakira", with parent company Puig, in 2010.[133] The brand has released two perfumes, "S by Shakira" and "S by Shakira Eau Florale," along with lotions and body sprays. She made her first terminal tattoo, which she dedicated to Pique, to promote a healthy way of making tattoos. At a release event for the first fragrance, Shakira stated: "The type of women who feel a connection with this fragrance would be independent and strong, but also a woman with a great capacity to love and a strong sense of who they are. It's for a woman who believes in herself." In 2012, she released a new fragrance "Elixir by Shakira", which was also available in the forms of "Paradise Elixir" and "wild Elixir". In 2014, she released a new perfume "Rock by Shakira".
Love Rocks app icon, which features Shakira holding a heart gem.

In September 17, 2015, she was featured as a playable bird in the game Angry Birds POP! for a limited time, and also in a special tournament in the game Angry Birds Friends after few weeks. In October 15, 2015, Love Rocks starring Shakira was the first video game that features the pop star.[134]
Personal life
	This section may contain an excessive amount of intricate detail that may only interest a specific audience. Please help relocate any relevant information, and remove excessive detail that may be against Wikipedia's inclusion policy. (December 2014)

Shakira is a native Spanish speaker who speaks fluent English and good Portuguese, as well as some Italian, French, Catalan and Arabic.[135][136][137] Shakira is a Roman Catholic,[138] and met Pope John Paul II in 1998. She is interested in world history, and she frequently studies the history and languages of the countries she visits.[139] After her Oral Fixation tour ended in the summer of 2007, Shakira attended a summer school class in Los Angeles at UCLA Extensions, where she took courses in History of Western Civilization. She used her middle names, Isabel Mebarak, and told the professor she was visiting from Colombia so as to avoid being recognized as a celebrity.[140] Shakira's cousin is a model, 2005–2006 Miss Colombia, Valerie Domínguez.[141][142] In an interview on The Paul O'Grady Show, she referred to herself as a mutt due to her diverse ancestry, which she noted as a theme behind her song "Gypsy".[143]

Shakira began dating Argentinian lawyer Antonio de la Rúa in 2000. In a 2009 interview, Shakira stated their relationship already worked as a married couple, and that "they don't need papers for that."[144] On January 10, 2011, Shakira announced on her website that after 11 years together, she and de la Rúa had separated in August 2010 after making "a mutual decision to take time apart from our romantic relationship." She wrote that the couple "view this period of separation as temporary and as a time of individual growth as we continue to be partners in our business and professional lives", with de la Rúa overseeing Shakira's "business and career interests as he has always done."[145] In September 2012, it was reported that de la Rúa planned to sue Shakira for $250 million, seeking monetary compensation for his work as her business manager as well as ownership of properties jointly held by the former couple.[146] De la Rúa eventually filed a lawsuit in California in April 2013, asking for $100 million he believes he is owed after Shakira suddenly terminated her business partnership with him in October 2011, ten months after they announced the end of their romantic relationship.[147]

Shakira is currently in a relationship with the Spanish football player Gerard Piqué, centre back for FC Barcelona and the Spanish national team.[148][149] They met in spring 2010 when Piqué appeared in the music video for Shakira's song "Waka Waka (This Time for Africa)", the official song of the 2010 FIFA World Cup.[146] Shakira officially confirmed their relationship on March 29, 2011 via Twitter and Facebook, posting a picture of the two with a caption reading, "I present to you my sunshine." It was the first time she had ever spoken of the relationship after several months of media speculation.[150] In September 2012, Shakira confirmed that she and Piqué were expecting their first child together.[151][152] Shakira gave birth to the couple's first son, Milan Piqué i Mebarak, on January 22, 2013 in Barcelona, Spain, where the family resides.[153] In January 2015, Shakira and Gerard Piqué hosted World Baby Shower to support UNICEF's work for children, inviting fans of the couple to share in their event by visiting a special website featuring 'Inspired Gifts' that directly benefit UNICEF's work for children in some of the poorest and remotest places on earth.[154] She gave birth to the couple's second son, Sasha Piqué i Mebarak, on January 29, 2015 in Barcelona, Spain.[155] The name Sasha is of Greek and Russian descent and means "defender of mankind" and "warrior." [156]
Activism
Main article: Pies Descalzos Foundation
Brazil's president Dilma Rousseff receiving a guitar for Shakira's charity auction (2011)

In 1997, Shakira founded the Pies Descalzos Foundation. It is a Colombian charity with special schools for poor children all around Colombia. It was funded by Shakira and other international groups and individuals. The name of the foundation is taken from Shakira's third studio album called Pies Descalzos, released in 1995. During her career, Shakira has performed at a large number of benefit concerts. In 2002 she sang at a Party in the Park concert fundraising for the Prince's Trust. That same year she performed at Divas Live which supports VH1's Save the Music Foundation. On July 2, 2005, she performed "Whenever, Wherever" and "La Tortura" on the Live 8 benefit concert at the Palace of Versailles, near Paris. On July 7, 2007, Shakira opened the German leg of Live Earth in Hamburg. Her set included "Don't Bother", "Inevitable", "Día Especial" (with Gustavo Cerati) and "Hips Don't Lie". Shakira also performed at the "Clinton Global Initiative", where she performed her hits "Underneath Your Clothes", "Inevitable" and "Hips Don't Lie". On May 17, 2008, Shakira and twenty other Latin American and Spanish artists performed in Buenos Aires and Mexico City to raise money for Shakira's Latin America in Solidarity Action "America Latina en Accion Solidaria" (ALAS Foundation) charity.[157] This concert attracted 150,000 people in Buenos Aires. Although tickets were free, the demand exceeded the supply; some fans who were fortunate enough to secure free tickets resold them.[158]
Shakira sings the National Anthem of Colombia at the Summit of the Americas in Cartagena, Colombia.

She has agitated against the implementation of the Arizona statute SB1070 against illegal immigration, saying that it goes against civil rights.[159] Shakira is a UNICEF Goodwill Ambassador and is one of their global representatives. "Shakira, like all our Goodwill Ambassadors, was chosen based on her compassion, her involvement in global issues, her deep commitment to helping children, and her appeal to young people around the world. We're very pleased to have Shakira join the UNICEF family. I know she'll help bring UNICEF's mission to the audience who will have the most impact on our future – young people themselves", said UNICEF's Executive Director Carol Bellamy.[160] In December 2007, Shakira visited Bangladesh to appeal for the victims of Cyclone Sidr. She spent 3 days with the victims and visited children affected by the disaster in schools built by UNICEF and participated in the distribution of family kits and warm clothes. She said that little was left of the school she visited in the village of Mirzapur, but it still provided an "oasis" for the children. "I am more convinced than ever that education is the key to so many of the difficulties that our children face in countries like mine or in developing countries like this one. It's the key to a better and safer world," she said.[161]

On April 3, 2006, Shakira was honored at a UN ceremony for creating the Pies Descalzos Foundation. At the event, Shakira said, "Let's not forget that at the end of this day when we all go home, 960 children will have died in Latin America."[162] On September 28, 2007, at the Clinton Global Initiative, it was revealed that Shakira received a commitment of $40 million from the Spanish government to help the victims of natural disasters. An additional $5 million was to be donated to four Latin American countries, to be spent on education and health. As part of the May 2007 concerts, her ALAS Foundation was able to solicit commitments of US$200 million from philanthropists Carlos Slim, Mexico's richest man, and Howard Buffett, son of U.S. investment guru Warren Buffett, Shakira announced on April 15, 2008.[163]
Shakira, Alejandro Sanz and Juan Carlos I, The King of Spain during the IberoAmerican Summit of El Salvador

Shakira served as the Honorary Chairperson for "Action Week" 2008 (April 21–27). The event is sponsored by the Global Campaign for Education (GCE), to generate awareness about the Education for All Act. She spoke to the U.S. Congress, British Prime Minister Gordon Brown, and World Bank President Robert Zoellick to promote a move towards Global Education. Angelina Jolie served as last year's chair. People En Español announced in their December 2008/January 2009 issue that Shakira is the "Humanitarian of the Year" as part of their "Las Estrellas del Año" (Stars of the Year) awards.[164] Shakira was also ranked at number 48 on the list of Top 50 Most Charitable Celebrities by OK! magazine. It reported that she donates approximately $55,000 to charity yearly.[165] On her 32nd birthday, Shakira opened a new $6-million school in her hometown Barranquilla, which was sponsored by herself and her Pies Descalzos Foundation.[166]

On December 7, 2009, Shakira was honored as a guest at the University of Oxford to give a speech about her work with children and education. She was chosen by the Oxford Union and joined the ranks of Albert Einstein, several US Presidents, Mother Teresa, and the Dalai Lama XIV, as a chosen speaker. During the speech, Shakira said, "That is how I want the youth of 2060 to see us: That our mission for global peace consisted of sending 30,000 educators to Afghanistan, not 30,000 soldiers. That in 2010, world education became more important than world domination."[167]

In March 2010, she was awarded a medal by the UN International Labor Organization in recognition of being, as UN Labor Chief Juan Somavia put it, a "true ambassador for children and young people, for quality education and social justice."[168] In November 2010, after performing as the opening act of the MTV European Music Awards, the Colombian singer also received the MTV Free Your Mind award for her continuing dedication to improve access to education for all children around the world.[169] In February 2011, the FC Barcelona Foundation and Pies descalzos reached an agreement for children's education through sport.[170] On October 5, 2011, US President Barack Obama announced that Shakira was appointed as a member of the White House Initiative on Educational Excellence for Hispanics.[171] Shakira was honored at the Latin Grammys as the Latin Recording Academy Person of the Year on November 9, 2011, for her philanthropy and contributions to Latin Music.[172]

""","English")
test.addDocument("""
Si le mot, sous la forme initiale franceis, est attesté en français dès le XIe siècle5, son usage comme nom de personne est plus tardif : c'est au XIIIe siècle qu'il apparaît, d'abord sous la forme italienne Francesco, dans certaines régions d'Italie en relations d'échanges avec la France. Il connaît à partir de là une expansion qui reflète celle de la popularité de François d'Assise6. On sait que celui-ci naquit et fut baptisé Giovanni en l'absence de son père, lequel ne voulait pas de ce prénom : de retour, il fit appeler son fils Francesco, « petit Français », en hommage au pays où il menait de fructueuses affaires et qui était aussi, croit-on, celui de sa femme, Dame Pica7. Plus tard, la réputation grandissante du saint et l'influence des Franciscains assurèrent le succès du nom bien au-delà de sa terre natale.

En France, c'est le rayonnement de la culture italienne au XVe siècle qui favorisa son adoption. En moins de cent ans, il se hissa au rang des prénoms les plus courants ; porté par des saints (François de Paule, François de Sales), des souverains (en France comme dans d'autres dynasties européennes : Bretagne, Lorraine, Toscane, Modène, Transylvanie, Parme, Saint-Empire, Autriche, Deux-Siciles, Liechtenstein), des écrivains (Villon, Rabelais, Malherbe, La Rochefoucauld, Fénelon, Voltaire, Chateaubriand), des musiciens (Couperin), des peintres (Boucher), des hommes politiques (Arago, Mitterrand), il resta près de quatre siècles durant parmi les dix prénoms les plus donnés6.

Au XVe siècle, la graphie François est commune au gentilé et au nom de personne, qui se prononcent encore tous deux [fʁɑ̃.swɛ] (« fransouè »). Mais pour le premier et suivant une tendance globale et ancienne dans l'usage populaire, la prononciation [fʁɑ̃.sɛ] (« fransè »), qui se diffuse particulièrement à partir du XVIe siècle, tend au XVIIe siècle à prévaloir et devient au XVIIIe siècle d'usage général. Parallèlement le prénom conserve la prononciation antérieure qui devient [fʁɑ̃.swa] (« fransoua ») à la fin du XVIIIe siècle. Ces évolutions divergentes se traduiront tardivement dans l'écriture : ce n'est qu'avec la réforme de l'orthographe appliquée à partir de l'édition de 1835 du dictionnaire de l'Académie française que l'on pourra distinguer, à l'écrit comme à l'oral, Français et François5.

Désormais, tous les ordinateurs lui étaient accessible. Les centrales nucléaires, les services informatiques des grandes compagnies, de l’eau, du téléphone, la télévision, l’électricité, la défense, la bourse...

Un long silence se fit dans la voiture. Le chauffeur regardait droit devant. David jeta un œil sur le compteur qui affichait 210km/h. L’autoroute était déserte. Depuis la construction de la Ligne Grande Vitesse, les gens préféraient prendre les transports en communs, plus rapide et moins chers. La LGV traversait la France d'un bout à l'autre avec un arrêt à Paris.

« A la base militaire du 57ème RA ? Mais qu’est-ce que j’ai à voir avec les militaires ? » David se rappelle y avoir fait un séjour alors qu’il avait vingt quatre ans. Il avait fait tout son possible pour éviter le service militaire, encore en vogue à l’époque, mais lorsqu’on lui avait proposé de travailler sur des projets informatiques secret défense, il n’avait pas su résister. Non pas que c’était passionnant, mais au moins, il ne faisait pas trop de sorti et il était tranquillement installé dans un bureau avec le matériel dont il rêvait.

Il sort de son lit, les yeux dans un brouillard Londonien, avance jusqu'à la salle de bain dont la baignoire a été remplie cinq minutes avant par l'ordinateur de la maison, et va directement prendre un bain. Un bain moussant comme tout les matins. Un bain bien chaud. Et comme il est trop grand pour sa baignoire, ses pieds dépassent. Quelques minutes plus tard, il s’endort. Aucun risque de noyade.

« Prélude m’avait dit qu’il désirait connaître l’amour. Les ordinateurs n’ont pas de sentiments et l’amour n’est que sentiments. Il y a bien l’amour physique, mais sans les sentiments, cela ressemble davantage à un instinct de reproduction qu’à de l’amour. Un ordinateur n’a pas ce besoin de reproduction. Et pourquoi m’avoir choisi ? »

Florence venait d’avouer quelque chose qu’elle n’osait même pas dire à la personne concernée : David. « Son » David. Oui, elle l’aimait. Depuis qu’il avait emménagé à côté de chez elle, il y a de ça cinq ans. Depuis le premier regard, elle savait que c’était lui. Et à chaque fois la même chose : dès qu’elle parlait de lui, dès qu’elle pensait à lui, ses yeux brillaient.

Les deux gardes du corps personnels de David le prirent par le bras et suivirent le général. Les militaires s‘étaient mis au « garde à vous » sur les côtés du couloir. Celui-ci menait à un ascenseur. Le général inséra à nouveau son badge et la porte s’ouvrit. Il y montèrent tous les quatre. Il n’y avait pas de niveau d’indiqué.

L’ascenseur démarra tout seul après que la porte se soit fermée. Il descendait. Il n’arrêtait pas de descendre. Puis, il s’arrêta enfin. La porte s’ouvrit. Et David eut la stupeur de sa vie. Devant lui se déployait un complexe informatique. Une vingtaine de personnes se déplaçaient d’un poste à l’autre regardant au passage les écrans géants muraux situés au fond de la salle. Il y avait bien une cinquantaine d’ordinateurs, cinq écrans géants et, situé entre les écrans géants et les ordinateurs, une machinerie impressionnante.

Il a recommencé et recommencé. Pratiquement tout les ordinateurs existants furent sous son contrôle. Il ne laissait pas de trace, ne se montrait pas. Et puis, il a découvert les dialogues en direct via Internet, le téléphone, la visio conférence, la domotique...

Florence est très excité à l’idée de se brancher sur un réseau militaire, mais en même temps, elle sait que cela va lui apporter des ennuis. Au moins, elle saura. Elle saura si David l’aime. Et en préparant le matériel demandé par Prélude, tout en pensant à David, elle se rappelle comment elle en est arrivée là.
Shakira
Page d'aide sur les redirections Pour l'album homonyme, voir Shakira (album).
Shakira
Description de cette image, également commentée ci-après

Shakira en 2014.
Informations générales Nom de naissance 	Shakira Isabel Mebarak Ripoll
Naissance 	2 février 1977 (38 ans)
Barranquilla, Drapeau de la Colombie Colombie
Activité principale 	Chanteuse, danseuse, auteure, compositrice, productrice, actrice
Genre musical 	Musique latine, pop, rock, dance
Instruments 	Guitare, harmonica, batterie, piano, djembé, darbouka
Années actives 	Depuis 1990
Labels 	Sony BMG, Epic, Roc Nation, EMI Latino
Site officiel 	shakira.com
Logo

modifier Consultez la documentation du modèle

Shakira, née Shakira Isabel Mebarak Ripoll le 2 février 1977 à Barranquilla, est une auteure-compositrice-interprète colombienne. Après avoir émergé sur la scène latino-américaine en se produisant dans les années 1990, elle connaît un succès international dès 2002 grâce au titre Whenever, Wherever et l'album Laundry Service. Célèbre pour ses chansons mélangeant pop latino et musique du monde, elle est également renommée pour ses talents de danseuse (danse orientale, merengue, tango).

Les chansons Whenever, Wherever et Hips Don't Lie sont ses deux plus grands succès avec respectivement 8 et 10 millions d'exemplaires vendus, se classant no 1 dans une trentaine de pays. En 2010, elle interprète Waka Waka (This Time for Africa), qui sera choisi par la FIFA comme chanson officielle de la Coupe du monde de football de 2010, et qui deviendra le single le plus vendu dans l'histoire de cet évènement (plus de 5 millions d'exemplaires1). Elle détient le record de ventes pour une artiste colombienne2 (80 millions)3, elle est également la seule artiste latino-américaine à avoir placé simultanément un titre à la première place des classements américains, australien et anglais4.

Son travail humanitaire est également reconnu, notamment au travers de son association Pies Descalzos5 (« Pieds nus » en espagnol), créée en 1997[Informations douteuses] [?], qui vient en aide aux enfants défavorisés dont les familles ont été victimes de groupes armés, en leur offrant un accès à l'éducation. Beaucoup de ses profits personnels (notamment ceux liés à la publicité) y sont reversés.

Sommaire

    1 Biographie
        1.1 De Magia à MTV Unplugged (1991–1999)
        1.2 Star mondiale et révélation Laundry Service (2001–2003)
        1.3 Fijación Oral Vol. 1 et 2, et She Wolf (2005–2009)
        1.4 Waka Waka et The Voice US (2010–2013)
        1.5 Shakira (depuis 2014)
    2 Style musical et influences
    3 Humanitaire
    4 Vie privée
    5 Discographie
    6 Filmographie
    7 Records et réalisations
    8 Distinctions
    9 Notes et références
    10 Voir aussi
        10.1 Bibliographie
        10.2 Liens externes

Biographie
Statue représentant Shakira à Barranquilla, en Colombie.

Shakira Isabel Mebarak Ripoll est née le 2 février 19776,7 à Barranquilla en Colombie, ville portuaire située au bord de la mer des Caraïbes, d'une mère colombienne (Nidia del Carmen Ripoll Torrado, d'ascendance espagnole (catalane) et d'un père américain, William Mebarak Chadid (né à New York) d'origine libanaise (de Zahlé au Liban). Enfant diagnostiquée hyperactive, elle prend du Ritalin8 et s'intéresse très tôt à la danse, qui lui permet de s'exprimer. Dès l'âge de 8 ans, elle compose sa première chanson, Tus gafas oscuras9, dédiée à son père qui portait des lunettes pour cacher sa tristesse d'avoir perdu un fils. Elle se présente à de nombreux concours et shows télévisés de sa région, notamment dans l'émission hebdomadaire Vivan los niños.

Grâce à sa productrice Monica Ariza, elle passe une audition devant Ciro Varga, qui propose la démo de Shakira à un producteur artistique de Sony. Ce dernier n'étant pas convaincu par la jeune chanteuse, un piège est tendu aux dirigeants de Sony : ils sont ainsi amenés dans un bar à Bogota où Shakira interprète 3 chansons. Séduits, ils signent alors un contrat pour enregistrer 3 disques.
De Magia à MTV Unplugged (1991–1999)

Le premier album de Shakira, Magia, est commercialisé le 24 juin 1991 en Colombie. Le disque n'est pas un grand succès commercial, mais permet à Shakira de se faire un nom dans son pays. À 16 ans, elle sort son deuxième album, Peligro. L'album se vendant mal, Shakira décide d'en arrêter la promotion malgré l'interprétation de la chanson Eres au festival Viña del Mar (Chili), récompensée d'une 3e place. Sa maison de disques lui fait comprendre que le troisième album prévu dans le contrat sera décisif : la chanteuse décide alors de faire une pause afin de se concentrer sur ses études. Elle apparaît toutefois de 1994 à 1997 dans la série télévisée El Oasis, où elle chante le générique avec un des autres acteurs. En 1996, l'album Pies Descalzos fait d'elle une star en Amérique latine et en Espagne, grâce notamment au single Estoy aquí : cinq millions d'exemplaires sont vendus, et elle remporte 3 Billboard Latin Music Awards, dont celui de l'album et de la révélation de l'année10.

Deux ans plus tard, paraît l'album ¿Dónde están los ladrones?, avec Emilio Estefan Jr. comme producteur exécutif9 et Shakira elle-même comme productrice artistique. L'album, avec les chansons Ciega, sordomuda et Ojos así (en duo avec le chanteur égyptien Amr Diab), augmente sa popularité et se vend à 7 millions d'unités11. Elle remporte deux Latin Grammy Awards, dont celui de la catégorie « Artiste de l'année ». Le live MTV Unplugged est enregistré le 12 août 1999 en Colombie, pendant une émission spéciale de la chaîne MTV. C'est un nouveau succès, avec 5 millions de disques vendus10. Elle commence alors à apprendre l'anglais et entame la tournée Tour Anfibio au printemps suivant.
Star mondiale et révélation Laundry Service (2001–2003)
Peinture sur un fourgon au Portugal imitant la pochette de Laundry Service, l'album le plus vendu de Shakira, sorti en 2001.

En 2001, Shakira s'associe avec le producteur Emilio Estefan, mari de la chanteuse Gloria Estefan, pour créer l'album Laundry Service, qui réalisera son rêve de carrière internationale : Whenever, Wherever, le premier single, connaît un succès mondial (tout comme la version espagnole, Suerte), devenant la chanson la plus vendue de l'année 2002 (8 millions d'exemplaires)12,13. Le single suivant, Underneath your clothes, suit le même succès (6e titre le plus vendu de 2002, avec 5 millions d'exemplaires)12 et conforte Shakira à la place de nouvelle star mondiale. Les chansons suivantes rencontrent également le succès : Objection (Tango), The One, Te Dejo Madrid et Que me quedes tu.

L'album, le plus vendu de la chanteuse, en date de 2012, s'écoule à 15 millions d'exemplaires dans le monde14. Pour permettre à son nouveau public international de connaître ses anciennes chansons parues en Amérique latine et en Espagne, sa maison de disques édite une compilation, Grandes Éxitos, qui sort le 5 novembre 200210. Trois jours plus tard, le 8 novembre 2002, à San Diego, la chanteuse commence une tournée mondiale de plus de 60 dates, Tour of the Mongoose, qui s'achève à Caracas le 11 mai 2003. Le DVD Live and off the Record, enregistré à Rotterdam le 22 avril 2003, est issu de cette tournée.
Fijación Oral Vol. 1 et 2, et She Wolf (2005–2009)
Shakira à Rock in Rio, Madrid, en 2008.

En 2005, Shakira revient avec La Tortura (un titre reggaetón qu'elle interprète avec Alejandro Sanz), qui introduit un album en 2 volumes : Fijación Oral Vol. 1, en espagnol, sorti le 6 juin, et Oral Fixation Vol. 2, en anglais, le 29 novembre. La Tortura est un succès : plus de 5,5 millions d'exemplaires vendues, et 5e plus grand succès de l'année 200515. Les chansons No, Dia de enero, La pared et Las de la intuicion poursuivent la promotion de l'album espagnol Fijación Oral Vol. 1, qui se vend à 4 millions d'unités à travers le monde10. Don't Bother, aux sonorités rock, est le premier single de Oral Fixation Vol.2.

En février 2006, elle enregistre un duo avec Wyclef Jean, Hips Don't Lie, et intègre la chanson à l'album : le titre deviendra le plus grand succès de la décennie, se classant no 1 dans 55 pays, et se vendant à plus de 10 millions d'exemplaires13. Elle en interprète un remix le 9 juillet pour la finale de la Coupe du monde de football de 2006. L'album connaît alors un regain d'intérêt et comptabilise 8 millions de ventes10, promu ensuite par le single Illegal en duo avec Carlos Santana. Le 14 juin 2006, Shakira commence sa nouvelle tournée, Oral Fixation Tour, à Saragosse en Espagne, pays dans lequel elle restera jusqu'en juillet avant de continuer en août et septembre aux États-Unis. Le DVD Live in Miami - Oral Fixation Tour sortira le 12 novembre 2007. Au printemps 2007, Shakira figure sur la réédition de l'album B'Day de Beyoncé, avec qui elle interprète en duo Beautiful Liar, un titre R'n'B, qui remporte un franc succès. Fin 2007, elle compose 2 chansons (Hay amores et La Despedida) pour la B.O du film L'Amour aux temps du choléra, tiré du roman éponyme de l'auteur colombien et ami de Shakira, Gabriel García Márquez16. En 2008, des parfums sont commercialisés en partenariat avec la compagnie Puig17,18.
Shakira, lors de sa tournée Sale el sol.

La chanteuse travaille ensuite sur son prochain album en anglais, s'entourant du producteur Pharrell Williams et de Wyclef Jean, avec qui elle avait déjà collaboré pour le tube Hips Don't Lie. En juin 2009, paraît le titre Loba (She Wolf en version anglaise), marquant une nouvelle orientation musicale, proche du disco des années Studio 5419. Produit en partie par The Neptunes, l'album She Wolf sort le 5 octobre 2009 (sauf aux États-Unis où sa sortie est repoussée au mois de novembre 2009, accompagnée d'un duo avec Lil Wayne produit par Timbaland, Give It Up to Me)20. Prenant un tournant artistique, Shakira mêle dans cet album sonorités électropop (She Wolf, Did It Again), électro (Men In This Town), jazz (Spy, en duo avec Wyclef Jean) et RnB (Long Time).

Les singles suivants sont Did It Again et Gypsy. La vidéo de ce dernier fait beaucoup parler d'elle avant même sa diffusion : le tennisman Rafael Nadal y est le partenaire de Shakira, ce qui fait alors naître la rumeur d'une idylle naissante dans de nombreux tabloïds, bien que la chanteuse soit à l'époque en couple avec Antonio de la Rúa21.
Waka Waka et The Voice US (2010–2013)
Shakira interprétant Sale el Sol à Montpellier en novembre 2010 au cours du The Sun Comes Out World Tour.

Le 10 juin 2010, Shakira participe au concert d'inauguration de la Coupe du monde de football de 2010 en Afrique du Sud avec d'autres artistes comme Alicia Keys, John Legend et les Black Eyed Peas22. La chanson Waka Waka (This time for Africa), spécialement enregistrée pour l'occasion avec le groupe sud-africain Freshlyground, est la musique officielle de la compétition. Comme en 2006, Shakira participe également à la cérémonie de clôture qui se déroule le 11 juillet23. La chanson est un succès mondial et permet à Shakira de revenir au premier plan après les ventes moyennes de l'album She Wolf. Waka Waka se vend à cinq millions d'exemplaires1, se classe premier dans une quarantaine de pays, et le clip devient la 3e vidéo la plus vue de tous les temps sur YouTube24.
Shakira le 19 août 2010 à Barcelone, lors du tournage du clip de Loca.

Son septième album (bilingue), Sale el sol, sort le 18 octobre 201025, avec comme 1er single Loca, disponible en version anglaise (avec le rappeur britannique Dizzee Rascal) et espagnole (avec le rappeur dominicain El Cata, auteur de la version originale de la chanson)26. La chanson est un succès en France, où elle se classe no 1 des téléchargements27 ; elle est par ailleurs à la 8e place des chansons les plus vendues de l'année 2010 (la première place allant à Waka Waka)28. Les singles suivants sont Sale el sol et Rabiosa. Ce dernier, comme Loca, bénéficiera de deux versions, l'une en espagnol avec El Cata, auteur de la chanson, et l'autre en anglais, avec Pitbull. La chanson atteint la 6e place des charts français29.
Shakira, sur scène à Paris, en 2010.

Alors que l'album Sale el sol atteint les 4 millions de ventes, Shakira obtient son étoile sur le Walk of Fame le 8 novembre 201130. Un mois plus tard, paraît le DVD du The Sun comes out World Tour, enregistré à Paris, soutenu par le titre Antes de las seis31. Elle enregistre une reprise de Je l'aime à mourir de Francis Cabrel, chanson qu'elle avait interprétée lors de ses concerts à Genève et à Paris. En décembre 2011, la chanson entre directement à la première place des charts français32 pour y rester 6 semaines consécutives33.

Au printemps 2012, paraît le cinquième single de Sale el sol, Addicted to You, suivi durant l'été par Get It Started, premier single du nouvel album de Pitbull, avec Shakira qui chante en duo. En 2013, elle participe à la quatrième saison de The Voice US. En effet, elle remplace la coache régulière Christina Aguilera. Le chanteur Usher remplace quant à lui Cee Lo Green. Adam Levine et Blake Shelton restent dans leurs fauteuils de coaches de The Voice. La quatrième saison débute le 25 mars 2013.
Shakira (depuis 2014)

En novembre 2011, Shakira déclara à propos de son dixième album : « J'ai déjà commencé à écrire de nouveaux morceaux que j'ai commencé à explorer dans le studio d'enregistrement à chaque fois que j'ai du temps à Barcelone et ici à Miami, je travaille avec différents producteurs et DJs... et j'essaie de trouver de nouvelles sources d'inspiration et de motivation. J'ai hâte de retourner en studio . Mon corps demande cela[réf. nécessaire]. » Elle travaille avec des producteurs tels que Benny Blanco, Tiësto, RedOne, Max Martin, Dr. Luke, LMFAO, Akon, Fernando Garibay, Sia, Ester Dean, Skrillex, The Runners, The Dream, Shea Taylor. À l'origine, le premier titre de son nouvel album devait être une chanson nommée Truth or Dare. Le clip est filmé à Lisbonne le 29 juin 2012. Mais en raison de sa grossesse inattendue, la sortie du single est reportée. Peter Edge, le PDG de RCA Records, déclare au magazine Billboard en octobre 2013 : « Il y a cette nouvelle chanson de Shakira qui va être un événement unique, nous prévoyons de la dévoiler avant la fin de 2013. » Néanmoins, le titre Can't Remember to Forget You est reporté au 13 janvier 2014, et l'artiste en vedette est Rihanna. Le dixième opus de la star dont ce morceau est extrait s'intitule Shakira et sort le 24 mars 2014 en France.

Le 24 février 2014, elle publie un nouveau titre promotionnel intitulé Empire. Le 14 avril, elle dévoile le troisième single Dare (La La La). Elle interprète ce titre réarrangé spécialement pour l'événement en duo avec Carlinhos Brown le 13 juillet 2014 lors de la cérémonie clôture de la coupe du monde de football de 2014. Le 18 juillet, elle devient la seule personnalité a dépasser les 100 millions de mentions « J'aime » sur Facebook. Plus tard dans le mois, elle est élue « femme la plus sexy de 2014 » par le magazine Men Health34.
Style musical et influences

Sa langue maternelle est l'espagnol, mais elle parle aussi couramment l'anglais, le portugais et le français, ainsi qu'un peu d'italien et d'arabe. Célèbre pour mélanger différents types de musique comme le folk, la pop ou encore le rock, elle déclara, un jour : « Ma musique est une fusion de plusieurs éléments différents. Et je suis toujours là à faire des expérimentations. Alors j'essaie de ne pas me limiter ou de me mettre dans une catégorie, ou... être l’architecte de ma propre prison »35. Ses précédents albums en espagnol, y compris Pies Descalzos et ¿Dónde están los ladrones?, sont des mélanges de musique folk et de rock latino, tandis que son album anglophone Laundry Service et ses derniers albums sont davantage influencés par le folklore latino-américain36. Son album de 2009, She Wolf est plus electro-pop, avec des touches de world music37, alors que Sale el sol propose un retour à ses débuts, entre ballades (Lo que más, Sale el sol, Antes de la Seis), chansons plus rock (Tu Boca, Devoción), et chansons rythmées latino (Loca, Rabiosa, Addicted to you)38,39.

Ayant grandi en écoutant beaucoup de musique orientale, celle-ci influence bon nombre de ses œuvres, comme Ojos así. Elle choisit également un thème indien pour sa performance de Hips Don't Lie aux MTV Video Music Awards 200640. Elle avoue d'ailleurs que « beaucoup de mes mouvements appartiennent à la culture arabe41 », et cite souvent ses parents comme contributeurs majeurs de son influence musicale41. Durant son enfance, Shakira préférait écouter du rock, comme Led Zeppelin42, The Beatles, Nirvana, The Police et U243, tout en vouant une admiration particulière à John Lennon44. Elle aurait également été profondément influencée par Prince, The Rolling Stones, AC/DC, The Who, The Pretenders, Red Hot Chili Peppers, The Cure, Tom Petty, Depeche Mode, The Clash et Ramones45,46.
Humanitaire
Shakira dans un centre d'aide à la petite enfance, Buenos Aires, 2011.

Le nom de la fondation que Shakira crée à 18 ans, en faveur des enfants colombiens défavorisés, est le même que celui de son 3e album, Pies Descalzos. Elle finance l'ouverture d'écoles et le don de nourriture à ceux dont les familles ont été la proie de groupes armés. Avec cette association, Shakira a déjà pu faire construire 6 écoles en Colombie47. Le 24 octobre 2003, à 26 ans, elle devient la plus jeune ambassadrice de l'Unicef48.

Le 3 avril 2006, elle est récompensée par l'ONU pour son travail humanitaire49. Le 27 avril de la même année, aux Latin Billboard Awards, elle est honorée par le Spirit of Hope Award pour son action au sein de sa fondation50. Le 12 décembre 2006, Shakira poursuit son combat pour les enfants et inaugure la fondation ALAS (América Latina Acción Solidaria) avec l'aide de nombreux artistes latino-américains, qui vise à donner accès à l'éducation aux enfants défavorisés d'Amérique Latine51.
Shakira accompagnée d'Antonio De La Rua, son ancien compagnon, et de Barack Obama en 2009.

Le 22 février 2010 elle lance un programme de financement de 300 millions $ pour un plan de développement destiné aux enfants d'Amérique Latine, en partenariat avec la Banque mondiale, nommé Initiative en faveur de la petite enfance : un investissement pour la vie52. Ce plan doit permettre de donner accès à une alimentation décente, aux soins, ainsi qu'à l'éducation à tous les enfants d'Amérique Latine de leur naissance jusqu'à leur 6 ans. À cette occasion, elle rencontre à la Maison-Blanche le président américain Barack Obama, ainsi que son vice-président Joe Biden pour les sensibiliser à ce programme53. Le 3 mars 2010, elle reçoit à Genève une médaille de la part de l'OIT pour son implication en faveur de la justice sociale47. En novembre 2010, elle tourne un spot publicitaire pour le vin espagnol Cava de la marque Freixenet, et s'engage à ce que ses 500 000 € de cachet soit reversés intégralement à son association pour financer la création d'une école en Colombie et une 2e à Port-au-Prince en Haïti54, pays qu'elle avait visité à la suite du séisme qui avait causé la mort de 230 000 personnes le 12 janvier 201055. Le 31 mars 2011, elle se rend à Haïti où elle fait un don de 400 000 $ et signe un accord avec la Banque interaméricaine de développement qui apportera la même somme pour permettre la reconstruction de l'école Elie Dubois à Port-au-Prince (l'une des plus anciennes du pays qui avait été construite au début du XXe siècle puis détruite à la suite du séisme)56.
Actuel compagnon de Shakira, Gerard Piqué, joueur de football au FC Barcelone.

À l'occasion de la Coupe du monde de football de 2010, Shakira devient l'ambassadrice de la campagne 1Goal : Education for All57, qui vise à assurer l'éducation aux 72 millions d'enfants non scolarisés à travers le monde, et plus particulièrement en Afrique58. Le titre Waka Waka figure sur l'album Listen Up! The Official 2010 FIFA World Cup Album sorti le 31 mai 2010, et dont tous les bénéfices sont reversés à 1Goal59. Le 28 février 2011, la Fondation du FC Barcelone et Pies descalzos annoncent un accord de coopération pour l'éducation des enfants à travers le sport60. Le 28 janvier 2012, Shakira a reçu en France la médaille de Chevalier de l’Ordre des Arts et des Lettres61.
Vie privée

En 2000, Shakira rencontre Antonio de la Rúa, le fils de l'ancien président d'Argentine Fernando de la Rúa. Il jouera un rôle important dans la carrière de Shakira, notamment en 2008, en négociant un contrat d'exclusivité de 10 ans avec Live Nation pour 70 à 100 millions de dollars62. Il est également derrière la campagne victorieuse de son père à la présidentielle d'Argentine et c'est à ce titre qu'il peut convoquer un certain nombre d'hommes d'affaires pour créer la fondation ALAS en 200663. Ils se séparent en août 2010 après 10 années de vie commune64.

Durant l'été 2010, Shakira rencontre le footballeur espagnol Gerard Piqué sur le tournage de son clip Waka Waka65. Le 29 mars 2011, elle confirme leur relation sur Twitter66.

En septembre 2012, Shakira annonce qu'ils attendent leur premier enfant67,68. Le 22 janvier 2013, elle donne naissance à un garçon, Milan Piqué Mebarak et le 29 janvier 2015 naît un deuxième garçon, Sasha Piqué Mebarak.

""","francais")









score = test.detect("Mythological ninth it mythological floor ninth than extreme of than.")
print score

